# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - "*"
pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      curl -O https://download.swift.org/swiftly/linux/swiftly-$(uname -m).tar.gz
      tar zxf swiftly-$(uname -m).tar.gz
      ./swiftly init --quiet-shell-followup --assume-yes
    displayName: "Install Swift"

  - script: |
      swift test
    displayName: "Run Tests"
