version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/" # Location of your Swift Package Manager project
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
